# Generated by Django 6.0.3 on 2026-03-10 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField(blank=True)),
                ('wpm', models.FloatField(default=0.0)),
                ('total_fillers', models.IntegerField(default=0)),
                ('filler_details', models.JSONField(default=dict)),
                ('pause_count', models.IntegerField(default=0)),
                ('total_pause_duration', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('ai_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analysis.audiofile')),
            ],
        ),
    ]
